/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace RendererService
{
  public abstract partial class Value : TAbstractBase {
    public abstract void Write(TProtocol protocol);
    public readonly bool Isset;
    public abstract object Data { get; }
    protected Value(bool isset) {
      Isset = isset;
    }

    public class ___undefined : Value {
      public override object Data { get { return null; } }
      public ___undefined() : base(false) {}

      public override void Write(TProtocol protocol) {
        throw new TProtocolException( TProtocolException.INVALID_DATA, "Cannot persist an union type which is not set.");
      }

    }

    public class strValue : Value {
      private string _data;
      public override object Data { get { return _data; } }
      public strValue(string data) : base(true) {
        this._data = data;
      }
      public override void Write(TProtocol oprot) {
        oprot.IncrementRecursionDepth();
        try
        {
          TStruct struc = new TStruct("Value");
          oprot.WriteStructBegin(struc);
          TField field = new TField();
          field.Name = "strValue";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(_data);
          oprot.WriteFieldEnd();
          oprot.WriteFieldStop();
          oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
      }
    }

    public class intValue : Value {
      private int _data;
      public override object Data { get { return _data; } }
      public intValue(int data) : base(true) {
        this._data = data;
      }
      public override void Write(TProtocol oprot) {
        oprot.IncrementRecursionDepth();
        try
        {
          TStruct struc = new TStruct("Value");
          oprot.WriteStructBegin(struc);
          TField field = new TField();
          field.Name = "intValue";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(_data);
          oprot.WriteFieldEnd();
          oprot.WriteFieldStop();
          oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
      }
    }

    public class boolValue : Value {
      private bool _data;
      public override object Data { get { return _data; } }
      public boolValue(bool data) : base(true) {
        this._data = data;
      }
      public override void Write(TProtocol oprot) {
        oprot.IncrementRecursionDepth();
        try
        {
          TStruct struc = new TStruct("Value");
          oprot.WriteStructBegin(struc);
          TField field = new TField();
          field.Name = "boolValue";
          field.Type = TType.Bool;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(_data);
          oprot.WriteFieldEnd();
          oprot.WriteFieldStop();
          oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
      }
    }

    public class doubleValue : Value {
      private double _data;
      public override object Data { get { return _data; } }
      public doubleValue(double data) : base(true) {
        this._data = data;
      }
      public override void Write(TProtocol oprot) {
        oprot.IncrementRecursionDepth();
        try
        {
          TStruct struc = new TStruct("Value");
          oprot.WriteStructBegin(struc);
          TField field = new TField();
          field.Name = "doubleValue";
          field.Type = TType.Double;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(_data);
          oprot.WriteFieldEnd();
          oprot.WriteFieldStop();
          oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
      }
    }

    public static Value Read(TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        Value retval;
        iprot.ReadStructBegin();
        TField field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop)
        {
          iprot.ReadFieldEnd();
          retval = new ___undefined();
        }
        else
        {
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                string temp;
                temp = iprot.ReadString();
                retval = new strValue(temp);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
                retval = new ___undefined();
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                int temp;
                temp = iprot.ReadI32();
                retval = new intValue(temp);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
                retval = new ___undefined();
              }
              break;
            case 3:
              if (field.Type == TType.Bool) {
                bool temp;
                temp = iprot.ReadBool();
                retval = new boolValue(temp);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
                retval = new ___undefined();
              }
              break;
            case 4:
              if (field.Type == TType.Double) {
                double temp;
                temp = iprot.ReadDouble();
                retval = new doubleValue(temp);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
                retval = new ___undefined();
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              retval = new ___undefined();
              break;
          }
          iprot.ReadFieldEnd();
          if (iprot.ReadFieldBegin().Type != TType.Stop)
          {
            throw new TProtocolException(TProtocolException.INVALID_DATA);
          }
        }
        iprot.ReadStructEnd();
        return retval;
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
    }

  }

}
