/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MtxRendererService
{
  public enum Direction
  {
    UP = 0,
    RIGHT = 1,
    DOWN = 2,
    LEFT = 3,
  }
}
