/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MtxRendererService
{
  public enum GroundTexture
  {
    NONE = 0,
    RANDOM = 1,
    GRAS = 2,
    WOOD = 3,
    ROCK = 4,
    SAND = 5,
    LAVA = 6,
    SNOW = 7,
    ICE = 8,
    EARTH = 9,
    METAL = 10,
    MARBLE = 11,
    PAVEMENT = 12,
    CONCRETE = 13,
  }
}
