/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MtxRendererService
{
  public enum WallTexture
  {
    RED_BRICKS = 0,
    WHITE_BRICKS = 1,
  }
}
